### ISSUE TITLE
Strang behavior with apache ab and concurrent requests

### ISSUE THREAD

**Issue by olivier-fs** [kamchatka-volcano/fcgi_responder#10] opened 2023-09-28 16:29 UTC
I get strange behavior when using apache ab with concurrent requests (i.e. -the -c flag)

Everything is fine when -c is not used i.e. 1000 requests => 1000 Status: 200 OK.

When -c is used, the last requests are blocked/delayed...
The number of blocked/delayed requests is the concurrency level minus 1
So
-n 10 -c 2 => 9 OK 1 timeout
-n 100 -c 2 => 99 OK 1 timeout
-n 100 -c 10 => 91 OK 9 timeout
-n 1000 -c 2 => 999 OK 1 timeout
-n 1000 -c 10 => 991 OK 9 timeout
-n 1000 -c 20 => 981 OK 19 timeout
...
You get the idea.

```
$ ab -s 10 -n 10 -c 2 http://127.0.0.1/fcgi/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...apr_pollset_poll: The timeout specified has expired (70007)
Total of 9 requests completed
```

```
$ ab -s 10 -n 100 -c 2 http://127.0.0.1/fcgi/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...apr_pollset_poll: The timeout specified has expired (70007)
Total of 99 requests completed
```

```
$ ab -s 10 -n 100 -c 10 http://127.0.0.1/fcgi/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...apr_pollset_poll: The timeout specified has expired (70007)
Total of 91 requests completed
```

```
$ ab -s 10 -n 1000 -c 10 http://127.0.0.1/fcgi/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 991 requests completed
```

Weirder:

I used ab -s 10 to shorten timeouts (be patient they say...)

But if I don't - or even use -s 60 to lengthen timeouts - then "blocked" requests come in... one by one i.e. no connection reuse : 1 accept, 1 request, 1 accept, 1 request, etc for all the "missing" requests that have been actually delayed rather than "missing".

I get the very same behavior with nginx-1.25.2 and httpd-2.4.57+mod_proxy_fcgi

If I disable connection reuse (i.e. no "fastcgi_keep_conn on;" in nginx.conf or no "enablereuse=on" in httpd.conf, then everything works as expected in ab.

But this kills one of the greatest features of FastCGI...

I have no clue what's going on... I have built the fcgi_responder.dll (very easy, thank you to use the great CMake) and the sample responder, I'm no FastCGI expert, but I know my nginx and httpd fastcgi setups are working with the classic fcgi C library.

I know cpp, so I may endup adding traces in the dll.

But what is strange for me is that you have explicit statement of using "ab -n 20000 -c 10 http://localhost:8088/" on the homepage, so I may be hiting a platform-specific issue.
I use TCP sockets on a Windows 10 box, with binaries built with latest VS 2019 Entreprise (cl 19.29.30152), latest CMake-3.27.6, latest boost-1.83.0 / asio-1.28.1 (same behavior wether asio or boost::asio).

Would you be kind enough to confirm/infirm that you see/don't see this very behavior on some of your dev boxes ?

**Comment by kamchatka-volcano** [comment] 2023-09-28 18:55
Hi, as you may have already noticed, the `fcgi_responder` examples are not well-maintained and were written hastily. I haven't used a blocking asio interface in any previous or subsequent projects, so this might just be a quirk in the connection implementation in the example. I will probably be able to check your version over the weekend, could you please provide a modified example that uses TCP sockets?

Also, could you build the [asyncgi](https://github.com/kamchatka-volcano/asyncgi) examples on Windows and check if the timeout issues persists with `example_hello_world.exe`? `asyncgi` is based on `fcgi_responder` and uses asynchronous asio TCP connections on Windows. I couldn't reproduce this problem with it. I also couldn't reproduce it with UNIX domain sockets on Linux, so I doubt that this is a problem with the protocol implementation.

**Comment by olivier-fs** [comment] 2023-09-29 09:31
Haha! Silly me I just saw "Jul 10" as the last commit and didn't bother check for other repos.

Of course a fully async lib is much better.

I always try do do a fully neutral test of a lib before commenting on design ; so these first tests results.

But I after some short experiments I came to the same conclusion you arleady did : Making it fully async needs a rewrite.

In process() an async_read with a completion handler would do the job ; so would a co_await if using C+20 coroutines, with the process() method launched by co_spawn().
But the infinite read_some() loop is not guaranted to read full records one-by-one. Under network pressure they could come fragmented. Then how to reassemble different fragments if async/coro and there is switching in the middle or records ?

sendData() is also intrinsically synchronous : You can't async_write or co_await here.

Trying to make a protocol lib fully network pluggable is hard and in fact quit impossible; In the end you get one way or another depending on a given lower-level network stack or async runtime... So better do it from the start and fully depend on asio.

(The same thing when I use Rust : The 2 main async HTPP stacks are each depending on a given async runtime : axum depends on tokio, actix-web depends on async-std... I coosed my poison and got fully depending on axum/tokio)

You spared me loosing time adding traces.

I'll try asyncgi ASAP and report... looks very promising.

Thank you!

**Comment by olivier-fs** [comment] 2023-09-29 09:44
BTW the slighlty modified example code using tcp::socket, that gets me the described behavior on Windows/MSVC/Winsocks2 :

[There is a small #ifdef for testing the webserver<->fcgiapp link : If I send and extra NULL the web server closes the connection, then reconnects, and the missing requests come along... shows that nothing is stucked/deadlocked, just one side is waiting for some event/data to come from the other side.]

```
#include <iostream>
#include <asio.hpp>
//#include <boost/asio.hpp>
#include <fcgi_responder/responder.h>

//namespace asio = boost::asio;
using tcp = asio::ip::tcp;

unsigned int request_count = 0;

class Connection : public fcgi::Responder {
public:
    explicit Connection(tcp::socket&& socket)
    : socket_(std::move(socket))
    {}

    void process()
    {
        while(isOpened_) {
            try {
                auto receivedDataSize = socket_.read_some(asio::buffer(buffer_));

                std::cout << "process: receivedDataSize=" << receivedDataSize << std::endl;

                receiveData(buffer_.data(), receivedDataSize);
            }
            catch(...){
                isOpened_ = false;
                return;
            }
        }
    }

private:
    void sendData(const std::string& data) override
    {
        /*size_t written = */ asio::write(socket_, asio::buffer(data, data.size()));
    }

    void disconnect() override
    {
        try {
            socket_.shutdown(tcp::socket::shutdown_both);
            socket_.close();
        }
        catch(const std::system_error &e) {
            std::cerr << "socket close error:" << e.code();
        }
        isOpened_ = false;
    };

    void processRequest(fcgi::Request&&, fcgi::Response&& response) override
    {
        std::cout << "processRequest #" << ++request_count << std::endl;

        std::string data(
            "Status: 200 OK\r\n" //#### NOT "HTTP/1.1 200 OK\r\n" !!
            "Content-type: text/html\r\n"
            "\r\n"
            "<html>HELLO WORLD USING ASIO!</html>"
        );

        response.setData(data);

        response.send();

#if 0 // This will make the web server close the connection. Ugly but very clear and effective hack
        char null[1] = {0};
        asio::write(socket_, asio::buffer(null, sizeof null));
#endif
    }

private:
    tcp::socket socket_;
    std::array<char, 65536> buffer_;
    bool isOpened_ = true;
};

int main ()
{
    asio::io_context io;
    tcp::acceptor acceptor(io, tcp::endpoint(tcp::v4(), 9991));

    unsigned int accept_count = 0;

    while (true) {
        auto socket = acceptor.accept();

        std::cout << "accept #" << ++accept_count << std::endl;
        Connection connection{std::move(socket)};
        connection.process();
    }

    return 0;
}
```

**Comment by kamchatka-volcano** [comment] 2023-09-29 17:32
Hah, no, you got it wrong) `asyncgi` doesn't have its own FastCGI implementation, it fully relies on `fcgi_responder` - check out [asyncgi/src/connection.h](https://github.com/kamchatka-volcano/asyncgi/blob/master/src/connection.h), it implements `fcgi::Responder` and uses async reads and writes.

`fcgi::Responder::receiveData` places data in a buffer and pops FastCGI records from it. All leftover data remains there for the next invocation, so the size of the received message doesn't really matter. It can process several records at once or only a single byte.
> Then how to reassemble different fragments

Each connection in `asyncgi` is handled by it's own `fcgi::Responder` instance, and the server doesn't send FastCGI messages of multiple requests over the same connection (there's a multiplexing mode in the protocol specification, but it's not supported by any server, as far as I know).

>sendData() is also intrinsically synchronous

And `asyncgi` handles it synchronously, by placing the data in the buffer) Then the asynchronous write loop works until this buffer has anything left.

**Comment by olivier-fs** [comment] 2023-09-29 19:59
Had some time to build asyncgi and make quick tests.

First things first : Works out of the box with nginx ! (example_hello_world)
- Nice logical components (server, router, url parser... great!)
- No more weird timeout / connection problems with ab and concurrent requests
- Excellent Time Per Request, as good as the threaded model from classic C fcgi lib
- Sligthly lower Requests per second, but I didn't experiment much at this point... I see that IOService uses a threadpool so it should not be related to "not all cores being used" to serve requests but I have yet to check.

example_hello_world uses an URL router that is much more powerful than raw strcmp() but may add some overhead.

Is it possible to run asyncgi without router ? (I see that Server ctor has a RequestProcessor param but I do not understand enough of the code at the moment. 

Then Apache http : same problem with bad header in response. But adding "Status: 200 OK\r\nContent-Type: text/plain\r\n\r\n" before "Hello world" doesn't work here :-(... Seems my header is removed, and may be some header is added elsewhere... will have a look to the code.

Third: sendData() . OK got it : it does not actually send, but fill buffer, so it's more like "setResponse" ; then yes an async pickup of buffer content does actual writes... Problem solved :-)

Feel free to close this issue if you wish, as I'll switch to asyncgi (but I get the idea that actual FCGI protocol is still handled by fcgi_responder ; may be the homepage should give pointer to asyncgi for actual examples/usage, and the synchronous example removed, as asyncgi is much more powerful (and maintained) than old-fashioned (and much less efficient) use of blocking calls...

P.S. Building asyncgi was easy again thanks to CMake, and your SealLake custom build works fine, but I definitely prefer classic find_package() over fetch remote content... Maybe CMakeLists option()s ?

**Comment by kamchatka-volcano** [comment] 2023-09-29 21:54
>I see that IOService uses a threadpool so it should not be related to "not all cores being used"

`asyncgi` is single threaded by default, pass `std::thread::hardware_concurrency()` to the `asio::IO` object to use all your cores.

>Is it possible to run asyncgi without router ? (I see that Server ctor has a RequestProcessor param

Yeah, `RequestProcessor` is just a requirement to be a callable with a signature `void(const asyncgi::Request& request, asyncgi::Response& response)`. Check `examples/example_request_processor.cpp`

>same problem with bad header

I'll look into it and address it in your other issue, couldn't get the Apache server working with FastCGI so far.

I'm also closing this issue, I'll try to check what's wrong with the blocking interface and timeouts later.

**Closed as completed by kamchatka-volcano** 2023-09-29 21:54 UTC
